apiVersion: v1
kind: Service
metadata:
  labels:
    component: web
    linkerd.io/extension: viz
    namespace: linkerd-viz
  name: web-ext
  namespace: linkerd-viz
spec:
  ports:
  - name: http
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    component: web
    linkerd.io/extension: viz
  type: LoadBalancer
