FROM node:14-slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./source/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./source .

ENV LCB_DATABASE_URI=mongodb://dynatrace:dynatrace2021@<ip>:27017 \
    LCB_HTTP_HOST=0.0.0.0 \
    LCB_HTTP_PORT=8080 \
    LCB_XMPP_ENABLE=false \
    LCB_XMPP_PORT=5222

EXPOSE 8080 5222

CMD ["npm", "start"]