apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-letschat
  name: mongo-letschat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-letschat
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-letschat
    spec:
      containers:
      - image: mongo
        name: mongo-letschat
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: dynatrace
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: dynatrace2021
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-letschat
  name: mongo-letschat-ext
spec:
  type: LoadBalancer
  selector:
    app: mongo-letschat
  ports:
  - protocol: TCP
    port: 27017
status:
  loadBalancer: {}
